name: Initialize Flutter Project

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: 'App name (must be in lowercase and use underscores, e.g., ottking_app)'
        required: true
        default: 'ottking_app'
      org_name:
        description: 'Package organization name (e.g., com.ottking)'
        required: true
        default: 'com.ottking'

jobs:
  create-project:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create New Flutter Project (Android Only)
        run: |

          find . -maxdepth 1 ! -name '.' ! -name '..' ! -name '.git' ! -name '.github' -exec rm -rf {} +
          

          flutter create --project-name=${{ github.event.inputs.project_name }} --org ${{ github.event.inputs.org_name }} --platforms=android .
          
      - name: Config Git and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Initialize default Flutter project (${{ github.event.inputs.project_name }}) for Android via GitHub Actions"
          git push origin main